---
# tasks for consul-template
- name: user
  user: name=consul
  tags:
  - consul-template
  - consul-template.user

- name: group
  group: name=consul
  tags:
  - consul-template
  - consul-template.group

- name: download binary
  get_url: url=https://github.com/hashicorp/consul-template/releases/download/v{{ version }}/consul-template_{{ version }}_linux_amd64.tar.gz
  args:
    force: true
    dest: "{{ tmp_dir }}"
    mode: 0644
    sha256sum: "{{ sha256sum }}"
  tags:
  - consul-template
  - consul-template.download

- name: unarchive
  unarchive: src={{ tmp_dir }}/consul-template_{{ version }}_linux_amd64.tar.gz dest={{ tmp_dir }} copy=no
  tags:
  - consul-template
  - consul-template.unarchive

- name: mv
  command: mv {{ tmp_dir }}/consul-template_{{ version }}_linux_amd64/consul-template {{ install_dir }}
  tags:
  - consul-template
  - consul-template.mv

- name: make it executable
  file: path={{ install_dir }}/consul-template owner=consul group=consul mode=0755 state=file
  tags:
  - consul-template
  - consul-template.chmod

- name: config file
  template: src=./consul-template.conf dest=/etc/consul-template.conf owner=consul group=consul mode=0644
  when: ansible_distribution_major_version in ["6", "7"]
  tags:
  - consul-template
  - consul-template.conf, consul-template.conf.config

- name: sysconfig file
  copy: src=./sysconfig dest=/etc/sysconfig/consul-template owner=consul group=consul mode=0644
  when: ansible_distribution_major_version in ["6", "7"]
  tags:
  - consul-template
  - consul-template.conf, consul-template.conf.sysconfig

- name: consul-template.service file
  copy: src=./consul-template.service dest=/etc/systemd/system/consul-template.service owner=consul group=consul mode=0644
  when: ansible_distribution_major_version in ["7"]
  tags:
  - consul-template
  - consul-template.conf, consul-template.conf.service

- name: service
  service: name=consul-template state={{ service_state }} enabled=yes
  tags:
  - consul-template
  - consul-template.service

